version: "3.9"
services:
    postgres:
        image: postgres:12
        restart: always
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: movus
            POSTGRES_PASSWORD: BtwIUseArch
            POSTGRES_DB: movus_auth
        ports:
            - "15432:5432"

    web:
        container_name: movus_auth_webserver
        image: nginx:latest
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
        ports:
            - 80:80
            - 443:443
        restart: always
    
    movus_auth:
        container_name: movus_auth
        build:
            context: ./auth-app
            dockerfile: Dockerfile
        volumes:
            - type: bind
              source: ./auth-app
              target: /app/auth
        restart: always
        
volumes:
    db_data: